export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as LandingPage} from "./LandingPage/LandingPage"
export {default as Navbar} from "./Navbar/Navbar"
export {default as Pricing} from "./Pricing/Pricing"
export {default as SiteLayout} from "./SiteLayout"
export {default as Login} from "./Login/Login"
